print('Hello, world!')
print(type('Hello, world!'))
print("Hello, world!")
print("Hello, 'world'!")
print('Hello, "world"!')
print('Hello,' + 'world!')
print('Hello, ' + 'world!')
print('Hello,' + ' world!')
print('1' + '1')
